# -*- coding: utf-8 -*-
"""xstk lab8 example

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RL6n8TDDUewT1Tbrz7M-TRAViQmqYlO6
"""

import pandas as pd
import numpy as np

df=pd.DataFrame({'number':[1,2,3],'color': ['red','white','blue']})
print(df)

df=pd.DataFrame({'number':[1,2,3],'color': ['red','white','blue']}, columns=['number','color'])
print('\n',df)

df=pd.DataFrame(np.random.randn(5,3), columns=['N1','N2','N3'])
print('\n',df)

df=pd.DataFrame({'N1':[1,2,3,4],'N2':[4,3,2,1]})
print('\n',df)

L=({'Name':'John','Last Name':'Smith'},{'Name':'Mary','Last Name': 'Wood'})
df=pd.DataFrame(L)
print('\n',df)

#access data
df=pd.DataFrame(np.random.randn(10,3),columns=['N1','N2','N3'])
print('\n',df)

df.head(5)

df.tail(5)

N2=df['N2']
print('\n',N2)
print('\n')

df[['N1','N2']]

print('\n',df[1:-2])