# -*- coding: utf-8 -*-
"""xstk lab8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wSdvSP8qg_S1gGW_WeaOJpPub1AKWi1c
"""

import pandas as pd
import numpy as np
import math

#read dataset
data=pd.read_csv("iris.csv",delimiter=',')
#print(data)

#show the first 5 data points
#data.head(5)

#number of data(count)
def Nodata(name):  
  count=0
  for i in data.index:
    count+=1
  return count

#mean
def ave(name):
  N1=data[name]
  sum=0
  for i in N1.index:
    sum=sum+N1[i]
  return sum/Nodata(name)



#standard deviation
def std(name):
  N2=data[name]
  sum=0
  for i in N2.index:
    sum=sum+(N2[i]-ave(name))*(N2[i]-ave(name))
    sigma=math.sqrt(sum/(Nodata(name)-1))
  return sigma



#min
def findmin(name):
  N3=data[name]
  min=N3[0]
  for i in N3.index:
    if N3[i]<min:
      min=N3[i]
  return min


#max
def findmax(name):
  N4=data[name]
  max=N4[0]
  for i in N4.index:
    if N4[i]>max:
      max=N4[i]
  return max

df=pd.DataFrame({'sepal_length':[Nodata('sepal_length'),ave('sepal_length'),std('sepal_length'),findmin('sepal_length'),findmax('sepal_length')],
                 'sepal_width':[Nodata('sepal_width'),ave('sepal_width'),std('sepal_width'),findmin('sepal_width'),findmax('sepal_width')],
                 'petal_length':[Nodata('petal_length'),ave('petal_length'),std('petal_length'),findmin('petal_length'),findmax('petal_length')],
                 'petal_width':[Nodata('petal_width'),ave('petal_width'),std('petal_width'),findmin('petal_width'),findmax('petal_width')]})
df.index=['count','mean','std','min','max']
print(df)

import pandas as pd
import numpy as np
import math
#read dataset
data=pd.read_csv("population.csv",delimiter=',')
#print(data)

#show the first 5 data points
#data.head(5)

#number of data(count)
def Nodata(name):
  count=0
  key=name
  for i in data.index:
    if(data[i]):
      count+=1
  return key
print(Nodata('Arab World'))
#mean
def ave(name):
  N1=data[name]
  sum=0
  for i in N1.index:
    sum=sum+N1[i]
  return sum/Nodata(name)



#standard deviation
def std(name):
  N2=data[name]
  sum=0
  for i in N2.index:
    sum=sum+(N2[i]-ave(name))*(N2[i]-ave(name))
    sigma=math.sqrt(sum/(Nodata(name)-1))
  return sigma



#min
def findmin(name):
  N3=data[name]
  min=N3[0]
  for i in N3.index:
    if N3[i]<min:
      min=N3[i]
  return min


#max
def findmax(y):
  N4=data[y]
  max=N4[0]
  for i in N4.index:
    if N4[i]>max:
      max=N4[i]
  return max


#df=pd.DataFrame({'Country Name':['Arab World'],'Mean':[ave('Year')]})
#print(df)