# -*- coding: utf-8 -*-
"""Lab5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F9hxNNyxOp66Q3vHzev3sD1-6vRtTlmf
"""

import random
import numpy as np
import math

#caua
x = list(np.random.choice([0,1,2,3,4,5], 3650, p=[0.1, 0.2, 0.3, 0.2, 0.15, 0.05]))
X = set(x)
print(X)

#caub
P = list([x.count(i)/len(x) for i in X])
print(P)

#cauc
EX = 0
for x in X:
  EX = EX + (x * P[x-1]);
print(EX)

VarX = 0
for x in X:
  VarX = VarX + (x-EX)*(x-EX)*P[x-1]
print(VarX)

SD = math.sqrt(VarX)
print(SD)

#caud
FX = sum(P[3:6])
print(FX)

import random
import numpy as np
import math

#a
x = []
for i in range(10000):
  x1 = random.randint(0,1)
  x2 = random.randint(0,1)
  u = x1 + x2
  x.append(u)
print(x)

#caub
X = set(x)
print(X)

#cauc
P = list([x.count(i)/len(x) for i in X])
print(P)

#caud
EX = 0
for x in X:
  EX = EX + (x * P[x-1]);
print(EX)

VarX = 0
for x in X:
  VarX = VarX + (x-EX)*(x-EX)*P[x-1]
print(VarX)

SD = math.sqrt(VarX)
print(SD)

#caue
FX = sum(P[1:3])
print(FX)