# -*- coding: utf-8 -*-
"""Ex1_Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115jaFfxX-dfe4YsFnKOuUTiCAyFrUf96
"""

import itertools

A = {1,2,3,4,5}
k = 3

n = len(A)
num_3_digit = list(itertools.permutations(A, k))
print("%i - permutations of %s: " %(k, A))
for i in num_3_digit:
  print(i)
num_length = len(num_3_digit)
print("Size = ", num_length)