# -*- coding: utf-8 -*-
"""Ex2_Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115jaFfxX-dfe4YsFnKOuUTiCAyFrUf96
"""

def cross(A, B):
  return {a + b for a in A for b in B}

urn = cross('W', '12345678') | cross('B', '123456') | cross('R', '123456789')

import itertools
#a
print("a)")
U3 = list(itertools.combinations(urn, 3))
len_U3 = len(U3)
for s in U3:
  print(s)
print(len_U3)

#b
print()
print("b)")
for s in U3:
  if s[0][0] != s[1][0] and s[1][0] != s[2][0] and s[2][0] != s[0][0]:
    print(s)
#c
print()
print("c)")
for s in U3:
  if s[0][0] == 'W' and s[1][0] == 'R':
    print(s)