# -*- coding: utf-8 -*-
"""Ex3_Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115jaFfxX-dfe4YsFnKOuUTiCAyFrUf96
"""

def cross(A, B):
  return {a + b for a in A for b in B}

books = cross('M', '1234') | cross('P', '123') | cross('C', '12') | cross('L', '1')

import itertools
list_books = list(itertools.permutations(books, 10))

n = 0
for s in list_books:
  count = 0
  for i in range(0,9):
    if s[i][0] != s[i+1][0]:
        count = count + 1
  if count == 3:
    print(s)
    n = n + 1
print(n)