# -*- coding: utf-8 -*-
"""Lab6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LdrcYo6anB2S0l5KSXepLs6yELgTHVFP
"""

import matplotlib.pyplot as plt
import math

def pmf_binom(k, n, p):
  c = math.factorial(n)/(math.factorial(k)*math.factorial(n-k))
  '''
  5C2 = 5!/(2!*(5-2)!)
  P(X = 2) = 5C2 * 0.1^2 * (1 - 0.1)^(5 - 2) ~= 0,0729
  '''
  return c*pow(p, k)*pow((1-p), (n-k))

def cau1(n, p):
  K = list(range(0, n + 1))
  P_binom = [pmf_binom(k, n, p) for k in K]
  plt.plot(K, P_binom, '-o')
  axes = plt.gca()
  axes.set_xlim([0, n])
  axes.set_ylim([0, 1.1 * max(P_binom)])
  plt.title('PMF of Bin(%i, %.2f)' %(n, p))
  plt.xlabel('Number k of successes')
  plt.ylabel('Probability of k successes')
  plt.show()

print(pmf_binom(2, 5, 0.1))
cau1(5, 0.1)

def pmf_poisson(k, lam):
  return (pow(lam, k)*pow(math.e, -lam))/math.factorial(k)
  '''
  Trung binh moi phut co 3 cuoc goi => lambda = 3
  Tinh xac xuat trung binh moi phut co 2 cuoc goi => n = 2
  p(2;3) = (3^2 * e^(-3))/2! ~= 0.224
  '''

def cau2(n, lam):
  K = list(range(0, n + 1))
  P_poisson = [pmf_poisson(k, lam) for k in K]
  plt.plot(K, P_poisson, '-o')
  plt.title('PMF of Poisson(%i)'%lam)
  plt.xlabel('Number of Event')
  plt.ylabel('Probability of Number of Event')

print(pmf_poisson(2, 3))
cau2(5, 3)

def pmf_geo(p, x):
  return p*pow(1-p, x -1)
  '''
  p(3) = P(X = 3) = 0.4(1-0.4)^3
  '''

def cau3(p, n):
  X = list(range(1, n + 1))
  P_geo = [pmf_geo(p, x) for x in X]
  plt.plot(X, P_geo, '-o')
  plt.title('PMF of Geometric(%.2f)'%p)
  plt.xlabel('n')
  plt.ylabel('Probability')

print(pmf_geo(0.4, 3))
cau3(0.4, 10)